apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: cop-pipeline
spec:
  params:
    - description: git url to clone
      name: git-source-url
      type: string
    - default: master
      description: "git revision to checkout (branch, tag, sha, ref…)"
      name: git-source-revision
      type: string
    - default: ./
      description: image path
      name: LOCAL_SCAN_PATH
      type: string
    - default: CRITICAL
      description: vulnerability severity level
      name: SEVERITY_LEVELS
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-source-url)
        - name: revision
          value: $(params.git-source-revision)
        - name: sslVerify
          value: "false"
        - name: noProxy
          value: "true"
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: app-source
    - name: build-artifact
      params:
        - name: GOALS
          value:
            - "-DskipTests"
            - package
            - "-Dquarkus.native.container-build=true"
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: app-source
        - name: maven-settings
          workspace: maven-settings
    - name: scan-build-artifact
      params:
        - name: ARGS
          value:
            - "--exit-code"
            - "1"
            - "--severity"
            - $(params.SEVERITY_LEVELS)
            - "filesystem"
        - name: IMAGE_PATH
          value: $(params.LOCAL_SCAN_PATH)
      runAfter:
        - build-artifact
      taskRef:
        kind: Task
        name: trivy-scanner
      workspaces:
        - name: manifest-dir
          workspace: app-source
  workspaces:
    - name: app-source
    - name: maven-settings
